/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as BSubdomainIndexRouteImport } from './routes/b.$subdomain.index'
import { Route as DashboardPropertiesIndexRouteImport } from './routes/dashboard.properties.index'
import { Route as DashboardPropertiesIdRouteImport } from './routes/dashboard.properties.$id'
import { Route as DashboardPropertiesNewRouteImport } from './routes/dashboard.properties.new'
import { Route as ApiPublicBrochureIdRouteImport } from './routes/api/public/brochure.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as BSubdomainPSlugRouteImport } from './routes/b.$subdomain.p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const BSubdomainIndexRoute = BSubdomainIndexRouteImport.update({
  id: '/b/$subdomain/',
  path: '/b/$subdomain/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPropertiesIndexRoute =
  DashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPropertiesIdRoute = DashboardPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesNewRoute = DashboardPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicBrochureIdRoute = ApiPublicBrochureIdRouteImport.update({
  id: '/api/public/brochure/$id',
  path: '/api/public/brochure/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BSubdomainPSlugRoute = BSubdomainPSlugRouteImport.update({
  id: '/b/$subdomain/p/$slug',
  path: '/b/$subdomain/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/p/$slug': typeof PSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/dashboard/properties/$id': typeof DashboardPropertiesIdRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/b/$subdomain/': typeof BSubdomainIndexRoute
  '/dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/api/public/brochure/$id': typeof ApiPublicBrochureIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$subdomain/p/$slug': typeof BSubdomainPSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/p/$slug': typeof PSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/dashboard/properties/$id': typeof DashboardPropertiesIdRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/b/$subdomain': typeof BSubdomainIndexRoute
  '/dashboard/properties': typeof DashboardPropertiesIndexRoute
  '/api/public/brochure/$id': typeof ApiPublicBrochureIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$subdomain/p/$slug': typeof BSubdomainPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/p/$slug': typeof PSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/dashboard/properties/$id': typeof DashboardPropertiesIdRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/b/$subdomain/': typeof BSubdomainIndexRoute
  '/dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/api/public/brochure/$id': typeof ApiPublicBrochureIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/b/$subdomain/p/$slug': typeof BSubdomainPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/refund-policy'
    | '/terms'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/p/$slug'
    | '/dashboard/'
    | '/api/public/cashfree-webhook'
    | '/dashboard/properties/$id'
    | '/dashboard/properties/new'
    | '/b/$subdomain/'
    | '/dashboard/properties/'
    | '/api/public/brochure/$id'
    | '/api/public/media/$'
    | '/b/$subdomain/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/onboarding'
    | '/pricing'
    | '/refund-policy'
    | '/terms'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/p/$slug'
    | '/dashboard'
    | '/api/public/cashfree-webhook'
    | '/dashboard/properties/$id'
    | '/dashboard/properties/new'
    | '/b/$subdomain'
    | '/dashboard/properties'
    | '/api/public/brochure/$id'
    | '/api/public/media/$'
    | '/b/$subdomain/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/refund-policy'
    | '/terms'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/p/$slug'
    | '/dashboard/'
    | '/api/public/cashfree-webhook'
    | '/dashboard/properties/$id'
    | '/dashboard/properties/new'
    | '/b/$subdomain/'
    | '/dashboard/properties/'
    | '/api/public/brochure/$id'
    | '/api/public/media/$'
    | '/b/$subdomain/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  BSubdomainIndexRoute: typeof BSubdomainIndexRoute
  ApiPublicBrochureIdRoute: typeof ApiPublicBrochureIdRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  BSubdomainPSlugRoute: typeof BSubdomainPSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$subdomain/': {
      id: '/b/$subdomain/'
      path: '/b/$subdomain'
      fullPath: '/b/$subdomain/'
      preLoaderRoute: typeof BSubdomainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/properties/': {
      id: '/dashboard/properties/'
      path: '/properties'
      fullPath: '/dashboard/properties/'
      preLoaderRoute: typeof DashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties/$id': {
      id: '/dashboard/properties/$id'
      path: '/properties/$id'
      fullPath: '/dashboard/properties/$id'
      preLoaderRoute: typeof DashboardPropertiesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties/new': {
      id: '/dashboard/properties/new'
      path: '/properties/new'
      fullPath: '/dashboard/properties/new'
      preLoaderRoute: typeof DashboardPropertiesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/brochure/$id': {
      id: '/api/public/brochure/$id'
      path: '/api/public/brochure/$id'
      fullPath: '/api/public/brochure/$id'
      preLoaderRoute: typeof ApiPublicBrochureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$subdomain/p/$slug': {
      id: '/b/$subdomain/p/$slug'
      path: '/b/$subdomain/p/$slug'
      fullPath: '/b/$subdomain/p/$slug'
      preLoaderRoute: typeof BSubdomainPSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPropertiesIdRoute: typeof DashboardPropertiesIdRoute
  DashboardPropertiesNewRoute: typeof DashboardPropertiesNewRoute
  DashboardPropertiesIndexRoute: typeof DashboardPropertiesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPropertiesIdRoute: DashboardPropertiesIdRoute,
  DashboardPropertiesNewRoute: DashboardPropertiesNewRoute,
  DashboardPropertiesIndexRoute: DashboardPropertiesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  BSubdomainIndexRoute: BSubdomainIndexRoute,
  ApiPublicBrochureIdRoute: ApiPublicBrochureIdRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  BSubdomainPSlugRoute: BSubdomainPSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
